import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	// icons
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<section className="paddingX paddingYShorter3">
					<Navbar />
					<div className="border-b my-2"></div>
					{children}
				</section>
				<Footer />
			</body>
		</html>
	);
}
4;
